apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: rental-chuck-norris
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    topicName: rental-chuck-norris
    cleanup.policy: compact
    retention.bytes: 107374182
    retention.ms: 86400000
    segment.bytes: 107374182