apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  bootstrapServers: 'my-cluster-kafka-bootstrap.amq-streams.svc.cluster.local:9092'
  image: quay.io/lbroudoux/debezium-connect:1.6.2.Final
  replicas: 1